#!/bin/bash

function pause(){
   read -p "$*"
}

#---------------------- START BELOW -------------------
echo 
echo 
echo "================================================================================================"
figlet Add SWAP space
echo "================================================================================================"
echo 
echo 
echo 
echo -n "This script will now create and configure SWAP space on this server"|pv -qL 30
echo 
echo 
pause "Press [Enter] key to start the process..."|pv -qL 20

# create a 2G swapfile
sudo fallocate -l 2G /swapfile

# change the permissions to root only
sudo chmod 600 /swapfile

# classify as SWAP FILE
sudo mkswap /swapfile

# turn SWAP on
sudo swapon /swapfile

# write to /etc/fstab to make SWAP permananet
echo "/swapfile   none    swap    sw    0   0" >> /etc/fstab

# set how often to use swap
sudo sysctl vm.swappiness=10

# Make Swappiness permanant by writing to file
echo "vm.swappiness=10" >> /etc/sysctl.conf

# set how much to cache
sudo sysctl vm.vfs_cache_pressure=50

# Make Cache permanant by writing to file
echo "vm.vfs_cache_pressure = 50" >> /etc/sysctl.conf

echo
echo "----------------------------------------------------------------------------------------------------"
echo
echo "Program finished"|pv -qL 20
echo
echo "----------------------------------------------------------------------------------------------------"
echo
echo "check below to see if 2G SWAP has been added."|pv -qL 20
echo

# show ram and SWAP
free -m



