#!/bin/bash

function pause(){
   read -p "$*"
}

#apt-get install figlet -y

#apt-get install pv -y

#---------------------- START BELOW -------------------
echo 
echo 
echo "================================================================================================"
figlet WP Extra Steps
echo "================================================================================================"
echo 
echo 
echo 
echo -n "This script will now run an update on the server then install the following programs:"|pv -qL 30
echo 
echo 
echo -e "php5\nphp5-curl\ncurl\nsendmail\n"|pv -qL 20

pause "Press [Enter] key to start the process..."|pv -qL 20



#apt-get update -y

#apt-get dist-upgrade -y

#apt-get install php5 -y

#apt-get install php5-curl -y

#apt-get install curl -y

#apt-get install sendmail -y

#cd ~/etc/
echo
echo "----------------------------------------------------------------------------------------------------"
echo
echo "Install finished"|pv -qL 20
echo
echo "----------------------------------------------------------------------------------------------------"
echo
echo "now do the following:"|pv -qL 20
echo
echo "run vi hosts"|pv -qL 20
echo
echo "Edit the first line from “127.0.0.1 localhost” to “127.0.0.1 localhost localhost.localdomain YOURHOSTNAME”"|pv -qL 30
echo
echo "then run sendmailconfig -y"|pv -qL 20
echo
echo

