#!/bin/bash

function pause(){
   read -p "$*"
}

# Install Figlet app (BOLD WRITING)
apt-get install figlet -y

# Install PV (TYPING EFFECT)
apt-get install pv -y

#---------------------- START BELOW -------------------
echo 
echo 
echo "================================================================================================"
figlet WP Extra Steps
echo "================================================================================================"
echo 
echo 
echo 
echo -n "This script will now run an update on the server then install the following programs:"|pv -qL 30
echo 
echo 
echo -e "php5\nphp5-curl\ncurl\nsendmail\n"|pv -qL 20

pause "Press [Enter] key to start the process..."|pv -qL 20

# Grab the Update
apt-get update -y

# run the update/upgrade
apt-get dist-upgrade -y

# Install 
apt-get install php5 -y

# Install 
apt-get install php5-curl -y

# Install 
apt-get install curl -y

# Install 
apt-get install sendmail -y

# Change directory to /etc 
cd ~/etc/

echo
echo "----------------------------------------------------------------------------------------------------"
echo
echo "Install finished"|pv -qL 20
echo
echo "----------------------------------------------------------------------------------------------------"
echo
echo "now do the following:"|pv -qL 20
echo
echo "run vi hosts"|pv -qL 20
echo
echo "Edit the first line from “127.0.0.1 localhost” to “127.0.0.1 localhost localhost.localdomain YOURHOSTNAME”"|pv -qL 30
echo
echo "then run sendmailconfig -y"|pv -qL 20
echo
echo

