#!/bin/bash

function pause(){
   read -p "$*"
}

# Install Figlet app (BOLD WRITING)
apt-get install figlet -y

# Install PV (TYPING EFFECT)
apt-get install pv -y

#---------------------- START BELOW -------------------
echo 
echo 
echo "================================================================================================"
figlet Install and Config
echo "================================================================================================"
echo 
echo 
echo 
echo -n "This script will do the following:"|pv -qL 30
echo 
echo 
echo -e "complete the next steps needed on initial install\ninstall required programs\nset up SWAP file\nconfigure php.ini\n"|pv -qL 20

pause "Press [Enter] key to start the process..."|pv -qL 20

bash /assets/installextra

bash /assets/createswap

echo
echo "----------------------------------------------------------------------------------------------------"
echo
echo "Program finished"|pv -qL 20
echo
echo "----------------------------------------------------------------------------------------------------"
echo




